name: Test ansible playbook

on: pull_request

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --deploy
    - name: Test playbook
      run: |
        pipenv check
        cd playbook && pipenv run ansible-playbook main.yml --syntax-check
