---
sudo: required

os: osx

env:
  - PYENV_ROOT=/tmp PIPENV_YES=1 PATH=$PYENV_ROOT:$PATH

before_install:
  - brew install pipenv

install:
  - pipenv install --dev

# We could use this to run and check idempotency, but for now we're
# doing a dry-run
# https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
script:
  - pipenv run ansible-lint playbook/main.yml
  - cd playbook && pipenv run ansible-playbook main.yml --syntax-check

before_deploy:
  # Set up git user name and tag this commit
  - export TRAVIS_TAG=$(pipenv run python version.py)
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_KEY
  draft: true
  on:
    branch: master

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
