---
sudo: required

os: osx

env:
  - PYENV_ROOT=/tmp PIPENV_YES=1 PATH=$PYENV_ROOT:$PATH

before_install:
  - brew install pipenv

install:
  - pipenv install --dev --deploy

# We could use this to run and check idempotency, but for now we're
# doing a dry-run
# https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
script:
  - pipenv check
  - cd playbook && pipenv run ansible-playbook main.yml --syntax-check

before_deploy:
  # Set up git user name and tag this commit
  - export TRAVIS_TAG=$(python $TRAVIS_BUILD_DIR/version.py)
  - git tag $TRAVIS_TAG

deploy:
  tag_name: $TRAVIS_TAG
  name: Release $TRAVIS_TAG
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_OAUTH_KEY
  on:
    branch: master
    tags: false

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_success: never
