---

- name: Create user config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    recurse: yes
    state: directory

- name: Updating fish configuration
  copy:
    src: "{{ fish_config_path }}"
    dest: "{{ ansible_env.HOME }}/.config/fish/config.fish"

- name: Updating vim configuration
  copy:
    src: "{{ gitconfig_path }}"
    dest: "{{ ansible_env.HOME }}/.gitconfig"

- name: Updating vimrc
  copy:
    src: "{{ vimrc_path }}"
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: Updating pylintrc
  copy:
    src: "{{ pylintrc_path  }}"
    dest: "{{ ansible_env.HOME  }}/.config/pylintrc"

- name: Updating npmrc
  copy:
    src: "{{ npmrc_path }}"
    dest: "{{ ansible_env.HOME }}/.config/.npmrc"
