---

- name: Create user config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    recurse: yes
    state: directory

- name: Updating fish configuration
  copy:
    src: "{{ fish_config_path }}"
    dest: "{{ ansible_env.HOME }}/.config/fish/config.fish"

- name: Copying .gitconfig file
  copy:
    src: "{{ gitconfig_path }}"
    dest: "{{ ansible_env.HOME }}/.gitconfig"

- name: Updating vimrc
  copy:
    src: "{{ vimrc_path }}"
    dest: "{{ ansible_env.HOME }}/.vimrc"
